### ISSUE TITLE
Exception trying to upload

### ISSUE THREAD

**Issue by jansorg** [own3d/bunny-cli#3] opened 2022-01-27 20:21 UTC
Although things worked a few weeks ago, it's failing with an exception today.

PHP: 
```text
$ php --version
PHP 8.1.2 (cli) (built: Jan 19 2022 17:12:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
```

Command used to upload:
```bash
bunny deploy --dir=public
```

Exception reported by the command above:
```
HP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/illuminate/collections/Collection.php:1459
Stack trace:
#0 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/illuminate/collections/Collection.php(13): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/.box/vendor/composer/ClassLoader.php(478): include('...')
#2 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/.box/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/illuminate/collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass()
#4 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#6 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/framework/src/Bootstrap/RegisterFacades.php(71): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#8 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(243): LaravelZero\Framework\Bootstrap\RegisterFacades->bootstrap()
#9 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#10 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/framework/src/Kernel.php(130): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/framework/src/Kernel.php(102): LaravelZero\Framework\Kernel->bootstrap()
#12 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/laravel-zero/framework/src/Kernel.php(89): LaravelZero\Framework\Kernel->ensureDefaultCommand()
#13 phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/bunny(36): LaravelZero\Framework\Kernel->handle()
#14 /home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny(14): require('...')
#15 /home/jansorg/.config/composer/vendor/bin/bunny(117): include('...')
#16 {main} in phar:///home/jansorg/.config/composer/vendor/own3d/bunny-cli/builds/bunny/vendor/illuminate/collections/Collection.php on line 13

```

**Comment by ghostzero** [comment] 2023-04-01 18:20
Fixed in 0.2.1. Duplicate of https://github.com/own3d/bunny-cli/issues/6.

**Closed as completed by ghostzero** 2023-04-01 18:20 UTC
